/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SoadFreylegastoseminario.ventanas;

/**
 *
 * @author ODETH
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        itemAgregarUsuario = new javax.swing.JMenu();
        itemIniciarSesion = new javax.swing.JMenuItem();
        itemInicairSesionUsuario2 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenu1 = new javax.swing.JMenu();
        itemReporte = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ejemplo CRUD BD");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        itemAgregarUsuario.setText("Usuario");
        itemAgregarUsuario.setToolTipText("");
        itemAgregarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAgregarUsuarioActionPerformed(evt);
            }
        });

        itemIniciarSesion.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        itemIniciarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/META-INF/iconos/sesion32px.png"))); // NOI18N
        itemIniciarSesion.setText("Cerrar Sesion");
        itemIniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemIniciarSesionActionPerformed(evt);
            }
        });
        itemAgregarUsuario.add(itemIniciarSesion);

        itemInicairSesionUsuario2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        itemInicairSesionUsuario2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/META-INF/iconos/agregar32px.png"))); // NOI18N
        itemInicairSesionUsuario2.setText("Agregar...");
        itemInicairSesionUsuario2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemInicairSesionUsuario2ActionPerformed(evt);
            }
        });
        itemAgregarUsuario.add(itemInicairSesionUsuario2);
        itemAgregarUsuario.add(jSeparator1);

        jMenu1.setText("REPORTES");

        itemReporte.setText("Todos los Usuarios");
        itemReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemReporteActionPerformed(evt);
            }
        });
        jMenu1.add(itemReporte);

        itemAgregarUsuario.add(jMenu1);

        jMenuBar1.add(itemAgregarUsuario);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemIniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemIniciarSesionActionPerformed
        // verificado
        VentanaLogin v = new VentanaLogin(this, true);
        v.setLocationRelativeTo(this);
        v.setVisible(true);
    }//GEN-LAST:event_itemIniciarSesionActionPerformed

    private void itemAgregarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAgregarUsuarioActionPerformed
        // verificado
        VentanaLogin v = new VentanaLogin(this, true);
        v.setLocationRelativeTo(this);
        v.setVisible(true);
       
    }//GEN-LAST:event_itemAgregarUsuarioActionPerformed

    private void itemInicairSesionUsuario2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemInicairSesionUsuario2ActionPerformed
        // verificado
        VentanaCrudUsuario v = new VentanaCrudUsuario(this,true);
        v.setLocationRelativeTo(this);
        v.setVisible(true);
    }//GEN-LAST:event_itemInicairSesionUsuario2ActionPerformed

    private void itemReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemReporteActionPerformed
       //verificado
       VentanaReporte v = new VentanaReporte (this,true);
       v.setLocationRelativeTo(this);
       v.setVisible(true);
    }//GEN-LAST:event_itemReporteActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // verificado
       VentanaLogin v = new VentanaLogin (this,true);
       v.setLocationRelativeTo(this);
       v.setVisible(true);
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu itemAgregarUsuario;
    private javax.swing.JMenuItem itemInicairSesionUsuario2;
    private javax.swing.JMenuItem itemIniciarSesion;
    private javax.swing.JMenuItem itemReporte;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
